API_BlogEngine/BlogEngine/Models/ContentViewModels/Posts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogEngine.Models.ContentViewModels
{
    public class Posts
    {
        [Key]
        public int PostId { get; set; }

        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Content")]
        public string Content { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime UpdatedDate { get; set; }

        public ApplicationUser User { get; set; }

        public ICollection<ManyPostCategory> Categories { get; } = new List<ManyPostCategory>();

        public ICollection<Comment> ChildComments { get; set; } = new List<Comment>();

    }
}

API_BlogEngine/BlogEngine/ViewModels/PostsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogEngine.ViewModels
{
    public class PostsViewModel
    {
        public int PostId { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime UpdatedDate { get; set; }

        public int ChildCommentCount { get; set; }

        public List<CategoryViewModel> Categories { get; set; }

        public string AuthorId { get; set; }

        public string AuthorName { get; set; }

    }
}

API_BlogEngine/BlogEngine/Controllers/BlogListController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using BlogEngine.Constants;
using BlogEngine.Models.ContentViewModels;
using BlogEngine.Services;
using BlogEngine.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace BlogEngine.Controllers
{
    public class BlogListController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        private readonly UserExtendManager _userService;
        private readonly IMapper _mapper;
        private IMemoryCache _cache;

        public BlogListController(IPostService postService, ICategoryService categoryService,
            IMapper mapper,IMemoryCache cache, UserExtendManager userService)
        {
            _postService = postService;
            _categoryService = categoryService;
            _userService = userService;
            _mapper = mapper;
            _cache = cache;
        }

        public async Task<IActionResult> Index()
        {
            var posts = await _postService.GetPostsAsync();
            var postsViewModel = _mapper.Map<List<PostsViewModel>>(posts);
            return Ok(postsViewModel);
        }

        public async Task<IActionResult> PostDetail(int postId)
        {
            var post = await _postService.GetPost(postId);
            var postViewModel = _mapper.Map<PostsViewModel>(post);
            return Ok(postViewModel);
        }

        public async Task<IActionResult> ViewByCategory(int id)
        {
            var posts = await _postService.GetPostsByCategoryIdAsync(id);
            var postsViewModel = _mapper.Map<List<PostsViewModel>>(posts);
            return Ok(postsViewModel);
        }

        [HttpGet]
        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> GetPostsOfUser()
        {
            var userIdClaim = User.FindFirst(JwtRegisteredClaimNames.Sid);
            var posts = await _userService.GetPostsOfUser(userIdClaim.Value);
            var postsViewModel = _mapper.Map<List<PostsViewModel>>(posts);
            return Ok(postsViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetPostsOfAuthor(string userId)
        {
            var posts = await _userService.GetPostsOfUser(userId);
            var postsViewModel = _mapper.Map<List<PostsViewModel>>(posts);
            return Ok(postsViewModel);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> CreatePost([FromBody]PostsViewModel model)
        {
            try
            {
                var userIdClaim = User.FindFirst(JwtRegisteredClaimNames.Sid);

                await _postService.CreatePost(model, userIdClaim.Value);

                var categories = await _categoryService.GetCategoriesAsync(CommonConstant.DefaultMaximumLoadedCategory, string.Empty);

                _cache.Set(CacheKeys.Categories, categories);
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return Ok(true);

        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> UpdatePost([FromBody]PostsViewModel model)
        {
            try
            {
                var userIdClaim = User.FindFirst(JwtRegisteredClaimNames.Sid);

                await _postService.UpdatePost(model, userIdClaim.Value);

                var categories = await _categoryService.GetCategoriesAsync(CommonConstant.DefaultMaximumLoadedCategory, string.Empty);

                _cache.Set(CacheKeys.Categories, categories);
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return Ok(true);

        }
    }
}

API_BlogEngine/BlogEngine/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BlogEngine.Models;
using BlogEngine.Services;
using BlogEngine.ViewModels;
using BlogEngine.Models.ContentViewModels;
using Microsoft.Extensions.Caching.Memory;
using BlogEngine.Constants;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.IdentityModel.Tokens.Jwt;

namespace BlogEngine.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        private IMemoryCache _cache;

        private readonly IMapper _mapper;


        public CategoryController(ICategoryService categoryService, IMemoryCache cache,IMapper mapper)
        {
            _categoryService = categoryService;
            _cache = cache;
            _mapper = mapper;
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> CreateCategory([FromBody]CategoryViewModel model)
        {
            var userIdClaim = User.FindFirst(JwtRegisteredClaimNames.Sid);
            var category= await _categoryService.AddCategoryAsync(model.CategoryName, userIdClaim.Value);
            var categoryModel = _mapper.Map<CategoryViewModel>(category);
            return Ok(categoryModel);
        }

        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> UpdateCategory([FromBody]CategoryViewModel model)
        {
            var category = await _categoryService.UpdateCategoryAsync(model.CategoryId, model.CategoryName);
            var categoryModel = _mapper.Map<CategoryViewModel>(category);
            return Ok(categoryModel);
        }

        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> DeleteCategory([FromBody]CategoryViewModel model)
        {
            var result = await _categoryService.DeleteCategoryAsync(model.CategoryId);
            return Ok(result);
        }


        public async Task<IActionResult> GetCategories(int topCategory, string userId)
        {
            var categories = new List<Category>();
            if (topCategory == 0)
            {
                categories = await _categoryService.GetCategoriesAsync(topCategory, userId);
            }
            else
            {
                categories = await _cache.GetOrCreateAsync(CacheKeys.Categories, async e =>
                {
                    var cachedCate = await _categoryService.GetCategoriesAsync(topCategory, userId);
                    return cachedCate;
                });
            }
            var viewModelCategories = _mapper.Map<List<CategoryViewModel>>(categories);
            viewModelCategories.ForEach(v =>
            {
                v.IsOwner = false;
                if (!string.IsNullOrEmpty(userId)) {
                    v.IsOwner = v.AuthorId == userId;
                }
            });
            return Ok(viewModelCategories);
        }
    }
}

API_BlogEngine/BlogEngine/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BlogEngine.Models;
using BlogEngine.Services;
using BlogEngine.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace BlogEngine.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly IPostService _postService;
        private readonly IMapper _mapper;

        public CommentController(ICommentService commentService,IPostService postService,IMapper mapper)
        {
            _mapper = mapper;
            _commentService = commentService;
            _postService = postService;
        }
        public async Task<IActionResult> GetComments(int postId)
        {
            var post = await _postService.GetPost(postId);
            var comments = post.ChildComments.ToList();
            var commentsViewModel = _mapper.Map<List<CommentViewModel>>(comments);
            return Ok(commentsViewModel);
        }

        [HttpPost]
        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> PostComment([FromBody]CommentViewModel comment)
        {
            var resultComment = await _commentService.CreateComment(comment);
            var commentModel = _mapper.Map<CommentViewModel>(resultComment);
            return Ok(commentModel);
        }

        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

API_BlogEngine/BlogEngine/Pages/Posts/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BlogEngine.Data;
using BlogEngine.Models.ContentViewModels;
using BlogEngine.Services;
using System.ComponentModel.DataAnnotations;

namespace BlogEngine.Pages.Posts
{
    public class DetailsModel : PageModel
    {
        private readonly IPostService _postService;

        public DetailsModel(IPostService postService)
        {
            _postService = postService;
        }

        public BlogEngine.Models.ContentViewModels.Posts Posts { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Posts = await _postService.GetPost(id.Value);

            if (Posts == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

API_BlogEngine/BlogEngine/Pages/Posts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogEngine.Data;
using BlogEngine.Models.ContentViewModels;
using BlogEngine.Services;
using BlogEngine.Controllers;
using System.ComponentModel.DataAnnotations;
using BlogEngine.ViewModels;
using Microsoft.Extensions.Caching.Memory;
using BlogEngine.Constants;

namespace BlogEngine.Pages.Posts
{
    public class EditModel : PageModel
    {
        private readonly IPostService _postService;

        private readonly ICategoryService _categoryService;

        private IMemoryCache _cache;

        private readonly UserExtendManager _userExtendManager;

        public EditModel(IPostService postService, ICategoryService categoryService, UserExtendManager userExtendManager,IMemoryCache cache)
        {
            _postService = postService;
            _userExtendManager = userExtendManager;
            _cache = cache;
            _categoryService = categoryService;
        }

        [BindProperty]
        public BlogEngine.Models.ContentViewModels.Posts Posts { get; set; }

        [BindProperty]
        [Display(Name = "Choose cateogies")]
        public string SelectedCategories { get; set; }

        public List<CategoryViewModel> Categories { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Posts = await _postService.GetPost(id.Value);

            if (_userExtendManager.GetUserId(User) != await _userExtendManager.GetUserIdAsync(Posts.User))
            {
                return RedirectToAction("Login", "Account");
            }

            if (Posts == null)
            {
                return NotFound();
            }
            SelectedCategories = string.Join(',', Posts.Categories.Select(x => x.CategoryId));
            await GetData();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                await GetData();
                return Page();
            }


            try
            {
                await _postService.UpdatePost(new PostsViewModel(), SelectedCategories);
                var categories = await _categoryService.GetCategoriesAsync(CommonConstant.DefaultMaximumLoadedCategory, string.Empty);
                _cache.Set(CacheKeys.Categories, categories);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (! await PostsExists(Posts.PostId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private async Task<bool> PostsExists(int id)
        {
            var post = await _postService.GetPost(id);
            return post != null;
        }

        private async Task GetData()
        {
            var categories = await _userExtendManager.GetSortedCategoriesByOwnerAsync(User);
            Categories = categories.Select(x => new CategoryViewModel { CategoryId = x.CategoryId, CategoryName = x.CategoryName }).ToList();
        }
    }
}

API_BlogEngine/BlogEngine/Pages/Posts/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using BlogEngine.Data;
using BlogEngine.Models.ContentViewModels;
using BlogEngine.Services;

namespace BlogEngine.Pages.Posts
{
    public class IndexModel : PageModel
    {
        private readonly UserExtendManager _userService;

        public IndexModel(UserExtendManager userService)
        {
            _userService = userService;
        }

        public IList<BlogEngine.Models.ContentViewModels.Posts> Posts { get;set; }

        public async Task OnGetAsync()
        {
            Posts = await _userService.GetPostsOfUser(string.Empty);
        }
    }
}

API_BlogEngine/BlogEngine/ViewComponents/AuthorViewComponent.cs
using BlogEngine.Models;
using BlogEngine.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogEngine.ViewComponents
{
    public class AuthorViewComponent : ViewComponent
    {
        private readonly UserExtendManager _userService;

        public AuthorViewComponent(UserExtendManager userService) { _userService = userService; }

        public IViewComponentResult Invoke(ApplicationUser user)
        {
            user.FullName = _userService.GetFullNameOrEmail(user);
            return View(user);
        }
    }
}

API_BlogEngine/BlogEngine/Pages/Posts/Details.cshtml
@page
@model BlogEngine.Pages.Posts.DetailsModel
@inject BlogEngine.Services.UserExtendManager manager;
@inject Microsoft.AspNetCore.Identity.SignInManager<BlogEngine.Models.ApplicationUser> SignInManager
@using BlogEngine.Controllers;

@{
    Layout = "_LayoutMain";
}
<section class="Material-blog-post-page section-padding">
    <div class="container">
        <div class="row">

            <div class="single-blog-page col-md-12 col-lg-8 col-xs-12">
                <article class="single-post wow fadeInUp animated animated animated" data-wow-delay=".2s" style="visibility: visible;-webkit-animation-delay: .2s; -moz-animation-delay: .2s; animation-delay: .2s;">

                    @if (manager.IsCurrentUserIsOwner(User, Model.Posts.User.Id))
                    {
                        <a asp-page="/Posts/Edit" asp-route-id="@Model.Posts.PostId" class="mt-3 btn btn-common float-right">@localizer["Edit"]<div class="ripple-container"></div></a>
                    }


                    <h2>@Model.Posts.Title</h2>
                    <div>@Html.Raw(Model.Posts.Content)</div>
                    <div class="single-post-meta">
                        <div class="post-tag">
                            @foreach (var c in Model.Posts.Categories)
                            {
                                <a asp-controller="BlogList" asp-action="ViewByCategory" asp-route-id="@c.CategoryId"><i class="material-icons mdi mdi-bookmark-outline"></i>@c.Category.CategoryName</a>
                            }

                        </div>
                        @*<div class="share-post">
                                <a href="http://preview.uideck.com/items/material-demo/blog-single.html#"><i class="fa fa-facebook"></i></a> <a href="http://preview.uideck.com/items/material-demo/blog-single.html#"><i class="fa fa-twitter"></i></a> <a href="http://preview.uideck.com/items/material-demo/blog-single.html#"><i class="fa fa-google-plus"></i></a> <a href="http://preview.uideck.com/items/material-demo/blog-single.html#"><i class="fa fa-pinterest"></i></a>
                            </div>*@
                    </div>
                </article>
                <vc:comment post-id="@Model.Posts.PostId" comment-id="0"></vc:comment>
               
            </div>

            <div class="col-md-12 col-lg-4 col-xs-12 blog-sidebar-column">

                <vc:author></vc:author>

                <vc:dock-category allow-manage="true" top-category="0"></vc:dock-category>

            </div>

        </div>
    </div>
</section>

@section Scripts{
    <script type="text/javascript">
      var showReply = '@Url.Action(nameof(CommentController.GetCommentChilds), "Comment")';
        var postCommentUrl = '@Url.Action(nameof(CommentController.PostComment), "Comment")';
        var userName = '@manager.GetUserName(User)';
        var email = '@(await manager.GetEmail(User))';
        var userId = '@manager.GetUserId(User)';
        var parentPostID=@Model.Posts.PostId;
    </script>
    <script src="@Url.Content("~/js/user.post.detail.js")"></script>
}

API_BlogEngine/BlogEngine/Pages/Posts/Edit.cshtml
@page
@model BlogEngine.Pages.Posts.EditModel

@{
    Layout = "_LayoutMain";
}
<section class="Material-blog-post-page section-padding section-dark">
    <div class="container">

        <div class="row ">
            <div class="col-md-8 box-shadow">
                <form id="editPost" method="post">
                    @Html.AntiForgeryToken()
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="Posts.PostId" />
                    <input type="hidden" asp-for="Posts.Categories" />
                    <input type="hidden" asp-for="Posts.CreatedDate" />
                    <div class="form-group">
                        <label asp-for="Posts.Title" class="control-label"></label>
                        <input asp-for="Posts.Title" class="form-control" />
                        <span asp-validation-for="Posts.Title" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="Posts.Content" class="control-label"></label>

                        <div>
                            <div asp-for="Posts.Content" class="form-control wys-content" />
                        </div>
                        <span asp-validation-for="Posts.Content" class="text-danger"></span>
                        <input type="hidden" id="postContentHidden" asp-for="Posts.Content" />
                    </div>
                    <div class="form-group">
                        <label asp-for="SelectedCategories" class="control-label"></label>
                        <input class="magicsearch" id="selectCategory" placeholder="Select categories...">
                        <input type="hidden" id="selectedCategories" asp-for="SelectedCategories" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@localizer["Update"]" class="btn btn-common" />
                    </div>
                </form>

            </div>
            <div>
                <a asp-page="./Index">@localizer["Back to List"]</a>
            </div>
        </div>



    </div>
</section>
@section Scripts {
    <script type="text/javascript">
        var categories =@Html.Raw(Json.Serialize(Model.Categories));
        $(function () {
            $('.wys-content').summernote({ height: 300 });
            $('.wys-content').summernote('code',$('#postContentHidden').val());
            $('#editPost').submit(function () {
                $('#postContentHidden').val($('.wys-content').summernote('code'));
                $('#selectedCategories').val($('#selectCategory').attr('data-id'));
            });
            $('#selectCategory').attr('data-id', $('#selectedCategories').val())
                .magicsearch({
                dataSource: categories,
                fields: ['categoryName'],
                id: 'categoryId',
                format: '%categoryName%',
                multiple: true,
                multiField: 'categoryName',
                noResult: 'No record',
                focusShow: true
            });

        });
    </script>
}

API_BlogEngine/BlogEngine/Pages/Posts/Index.cshtml
@page
@model BlogEngine.Pages.Posts.IndexModel
@using BlogEngine.Controllers;
@{
    Layout = "_LayoutMain";
}
@inject BlogEngine.Services.UserExtendManager UserManager
<section class="Material-blog-post-page section-padding">
    <div class="container">
        <div class="row">

            <div class="col-md-12 col-lg-8 col-xs-12 blog-post-column">
                <div class="row">
                    @Html.Partial("Partials/PostItem", Model.Posts)

                    <div class="col-md-12 text-center mt-3 blog-pagination wow animated fadeInUp" data-wow-delay=".4s" style="visibility: hidden; -webkit-animation-name: none; -moz-animation-name: none; animation-name: none;-webkit-animation-delay: .4s; -moz-animation-delay: .4s; animation-delay: .4s;">
                        <a href="javascript:void(0)" class="btn btn-common"><i class="material-icons mdi mdi mdi-autorenew"></i> Load More Stories<div class="ripple-container"></div></a>
                    </div>

                </div>
            </div>


            <div class="col-md-12 col-lg-4 col-xs-12 blog-sidebar-column">

                <vc:author user="@await UserManager.GetUserAsync(User)"></vc:author>

                <div id="listCategory">
                    <vc:dock-category allow-manage="true" top-category="0"></vc:dock-category>
                </div>
            </div>

        </div>
    </div>
</section>
@section Scripts{
    <script type="text/javascript">
        var addNewCategoryUrl = '@Url.Action(nameof(CategoryController.CreateCategory), "Category")';
        var updateCategoryUrl = '@Url.Action(nameof(CategoryController.UpdateCategory), "Category")';
        var deleteCategoryUrl='@Url.Action(nameof(CategoryController.DeleteCategory), "Category")';
    </script>
    <script src="@Url.Content("~/js/user.category.js")"></script>
}